-- MySQL Script generated by MySQL Workbench
-- Thu Jun  9 17:47:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema request_card
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema request_card
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `request_card` DEFAULT CHARACTER SET utf8 ;
USE `request_card` ;

-- -----------------------------------------------------
-- Table `request_card`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `request_card`.`people` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `document_type` ENUM('CC', 'TI', 'CE', 'PAS', 'NIS', 'PEP', 'NIT') NOT NULL,
  `document_number` VARCHAR(17) NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `last_name` VARCHAR(99) NOT NULL,
  `blood_type` ENUM('A', 'AB', 'B', 'O') NOT NULL,
  `rh` ENUM('+', '-') NOT NULL,
  `photo` VARCHAR(67) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `request_card`.`card_applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `request_card`.`card_applications` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `person_id` BIGINT(20) NOT NULL,
  `status` ENUM('Enviada', 'En proceso', 'Rechazada', 'Impreso', 'Entregado') NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `person_id_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `request_card`.`people` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `request_card`.`group_bosses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `request_card`.`group_bosses` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `last_name` VARCHAR(99) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `request_card`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `request_card`.`groups` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `group` VARCHAR(10) NOT NULL,
  `name` VARCHAR(67) NOT NULL,
  `group_boss_id` BIGINT(20) NOT NULL,
  `status` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `groupe_boss_id_idx` (`group_boss_id` ASC) VISIBLE,
  CONSTRAINT `groupe_boss_id`
    FOREIGN KEY (`group_boss_id`)
    REFERENCES `request_card`.`group_bosses` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `request_card`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `request_card`.`roles` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `role` ENUM('Aprendiz', 'Instructor', 'Administrativo') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `request_card`.`person_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `request_card`.`person_role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `person_id` BIGINT(20) NOT NULL,
  `role_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `person_id_role_idx` (`person_id` ASC) VISIBLE,
  INDEX `role_id_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `person_id_role`
    FOREIGN KEY (`person_id`)
    REFERENCES `request_card`.`people` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `request_card`.`roles` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `request_card`.`person_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `request_card`.`person_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `person_id` BIGINT(20) NOT NULL,
  `group_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `person_id_group_idx` (`person_id` ASC) VISIBLE,
  INDEX `group_id_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `request_card`.`groups` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `person_id_group`
    FOREIGN KEY (`person_id`)
    REFERENCES `request_card`.`person_role` (`person_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
